# Generated by Django 4.1 on 2024-06-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='access_tok_valid',
            field=models.DateTimeField(null=True),
        ),
    ]
